# -*- coding: utf-8 -*-
"""score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdlzW-hC3S1rgyQNeJiqCgJ1WYAlj1iM
"""

a = input()
b = a.split()
nopass = []
for i in b:
  if int(i) < 60:
   nopass.append(int(i))
print("不及格:",nopass)
max = 0
min = 100
for i in b:
  num = int(i)
  if num > max :
    max = num
  if num < min :
    min = num
print("最大值:",max,sep="")
print("最小值:",min,sep="")