# -*- coding: utf-8 -*-
"""score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQnFZ5eWBm4D3vFATG69X4PmqE5PJXME
"""

a = input()
b = a.split()
nopass = []
for i in b:
  if int(i) < 60:
   nopass.append(int(i))
print("不及格:",nopass)
b = list(map(int, b))
average = sum(b) / len(b)
print(average)