# -*- coding: utf-8 -*-
"""score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zLsd1hzn6n6JkJA74YadRAll0CKONW1
"""

a = input()
b = a.split()
nopass = 0
for i in b:
  if int(i) < 60:
   nopass += 1
print("不及格:",nopass,sep="")
b = list(map(int, b))
average = sum(b) / len(b)
print("平均:",average,sep="")
print("不及格:",nopass,sep="")
max = 0
min = 100
for i in b:
  num = int(i)
  if num > max :
    max = num
  if num < min :
    min = num
print("最大值:",max,sep="")
print("最小值:",min,sep="")
